### ISSUE TITLE
How to work with nextjs

### ISSUE THREAD

**Issue by jeffreys-cat** [resetsix/react-monaco-sql-language-demo#1]
I add the follow code to next.config.js, but it seems not work

![image](https://github.com/resetsix/react-monaco-sql-language-demo/assets/11832969/4be54124-0498-411b-9e1d-5b945f18b90c)

**Comment by resetsix** [comment]
> I add the follow code to next.config.js, but it seems not work
> 
> ![image](https://private-user-images.githubusercontent.com/11832969/340979188-4be54124-0498-411b-9e1d-5b945f18b90c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODY0NDIsIm5iZiI6MTcxODc4NjE0MiwicGF0aCI6Ii8xMTgzMjk2OS8zNDA5NzkxODgtNGJlNTQxMjQtMDQ5OC00MTFiLTllMWQtNWI5NDVmMThiOTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA4MzU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMGFlNjI3NTMwZjY4MTE0YTkwMjc0ZDg1OWRhYWViN2Q2MGMxZGMzNzY2N2Q5Y2FmMmQxMTU0ZWUyMTQwMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wsZvKEYvtgAxy03j7Dbj-qQhL1UPee7m3bOKYOhioFo)

You can try adding the following configuration to the entry of the root component
```typescript
// index.tsx
import { loader } from "@monaco-editor/react";
import * as monaco from "monaco-editor";

loader.config({ monaco });
```

**Comment by jeffreys-cat** [comment]
@resetsix Thanks a lot! It seems works!
